package app.ui.sensors.actions;

public enum ActionCode {
    SIMULATION_WINDOW,
    SIMULATION_SAVE,
    SIMULATION_RECORD,
    SIMULATION_PAUSE,
    SIMULATION_LOAD,

    POPUP_SUBMIT,

    BRUSH_CREATE_POPUP,
    BRUSH_CREATE_SUBMIT,
    PRESET_SOLID,
    PRESET_LIQUID,
    PRESET_GAS,
    PRESET_WALL,

    ERASER_ACTION,
    REMOVE_WALL_ACTION,

    CONFG_THREADS,

    ABOUT_INFO,

    VIEW_PRESSURE,
    VIEW_VECTORS,

    PLATFORM_DOWNLOAD,
    PRESET_USED, VIEW_SPECTRUM, CHANGE_BACKGROUND, ENABLE_SPRITES, CANCEL_WINDOW, PLATFORM_OPEN
}
